adventureworks:
  target: postgres
  outputs:
    postgres:  
      type: postgres
      host: postgres
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: public
      threads: 12